### ISSUE TITLE
Inject js scripts

### ISSUE THREAD

**Issue by thebiltheory** [mohamdio/slush-kickstart#1]
Hi, 

First, I like the kickstarter. However I don't really get the js in sources injected in the index. 

Cheers.

**Comment by mohamdio** [comment]
Hi, first thanks for using kickstart
second : 
i tested this and appear working fine ( http://jmp.sh/9NqxtdT ), just start `gulp` task and add some codes in your js files to test changes in sources tab.

**Comment by thebiltheory** [comment]
I figured how inject the bower-files but, still seems having issues. 

I inject all the modules this way. 
[ http://pasteboard.co/1e7beBnT.png ]

But seems jquery doesn't want to be loaded. 
I get the following error when I inject all the modules
[ http://pasteboard.co/1e7q8ksI.png ]

Actually any of the scripts seems working.

**Comment by mohamdio** [comment]
Because bootstrap wants jQuery global, so will require it like that : 
```javascript
window.jQuery = $ = require('../vendor/jquery');
```
and will working fine.

**Comment by thebiltheory** [comment]
Thank you so much @mohamdio! Everything is working fine!
