### ISSUE TITLE
Framework choice

### ISSUE THREAD

**Issue by thebiltheory** [mohamdio/slush-kickstart#2]
Hey @mohamdio,

I've quite adopted this workflow and I found a nice light framework recently and I thought it would be cool to make it as a framework choice. 

https://github.com/jgthms/bulma 

Cheers,

**Comment by mohamdio** [comment]
Hi,
i updated the package to v1.0.2 which now support bulma framework, so you just need to update slush-kickstart package by doing that:
`npm install -g slush-kickstart`
or
`npm update -g`
and you will get the new choice [ http://jmp.sh/DQ6yV00 ]

regards
