### ISSUE TITLE
kickstarting breaks

### ISSUE THREAD

**Issue by violacase** [mohamdio/slush-kickstart#5]
Hi there.

Centos 7
node v5.8.0
npm 3.7.3

Command 'slush kickstart'  breaks with error:

/usr/lib/node_modules/slush-kickstart/slush/defaults.js:37
        authorName: user.name || '',
                        ^

TypeError: Cannot read property 'name' of undefined

**Comment by mohamdio** [comment]
Hi,

i think i know why happened this issue, so we need to test small new code in this file [ slush/default.js ]
so just change this code: [https://github.com/mohamdio/slush-kickstart/blob/v1.0.2/slush/defaults.js#L30]
```
if (fs.existsSync(configFile)) {
        user = iniparser.parseSync(configFile).user || {};
}
```
to
```
user = fs.existsSync(configFile) ? iniparser.parseSync(configFile).user : {};
```
and tell me if this solved the issue or not ? to make update about that.

regards

**Comment by violacase** [comment]
Hi,

I'm just the messenger, not a contributor.
Testing and publishing is your job I think.
Btw: the above mentioned function is called 'setDefautls()'. That's a bit silly. Should be 'setDefaults()' I assume.

**Comment by mohamdio** [comment]
Okay, i tested and updated the package to v1.0.3, so you can update it now by doing that:
`npm install -g slush-kickstart`
or
`npm update -g`
this update will solve the issue

thanks for your feedback

**Comment by violacase** [comment]
Don't forget to update your repo. I don't see any updates.

**Comment by mohamdio** [comment]
I already updated the repo and npm package also, check out : 
https://github.com/mohamdio/slush-kickstart/commit/2fc7ca6c19b69c70af9a46b0e0ada908e8a80d30
https://www.npmjs.com/package/slush-kickstart
so did you tried package again ? or you didn't get the new update ?

regards

**Comment by violacase** [comment]
Ok, sorry... Just saw you updated. I'll try and let you know.

**Comment by mohamdio** [comment]
so the new update solve this issue .. right ?
