### ISSUE TITLE
Gulp breaks

### ISSUE THREAD

**Issue by violacase** [mohamdio/slush-kickstart#6]
Hi,

After successfully(?) scaffolding then running gulp it breaks with:

[13:58:38] 'bower:js' errored after 17 ms
[13:58:38] Error: Bower components directory does not exist at /var/www/vhosts/violacase.nl/httpdocs/slush.mijnspeelplek.com/bower_components
    at Error (native)
    at Object.module.exports (/var/www/vhosts/violacase.nl/httpdocs/slush.mijnspeelplek.com/node_modules/main-bower-files/lib/index.js:76:17)

A bower_components directory has not been created.

Regards

**Comment by mohamdio** [comment]
Hi, 
this mean you didn't installed bower components, so did you start kickstart by this : 
```
slush kickstart --skip-install
```
if yes so you need to run this : 
```
bower install
```
please check this : 
https://github.com/mohamdio/slush-kickstart#getting-started

**Comment by violacase** [comment]
I didn't slushed kickstart with `--skip-install.` param.
Also ` bower install`doesn't perform any action.

**Comment by mohamdio** [comment]
did you have `bower.json` file inside your project folder ? if yes the command `bower install` should install all components inside the folder.

**Comment by violacase** [comment]
Contents of bower.json:

```
{
  "name": "kickstart",
  "description": "none",
  "private": true,
  "ignore": [
    "**/.*",
    "node_modules",
    "bower_components",
    "test",
    "tests"
  ],
  "dependencies": {
     
    "foundation-sites": "~6.0.5",
    
    
    "font-awesome": "~4.5.0",
    
    
    
    
    
    
    
    "jquery": "~2.1.4"
  },
  "overrides": {
    
    "foundation-sites": {
      "main": [
        "scss/**/*.scss",
        "dist/foundation.css",
        "dist/*.js"
      ]
    },
    
    
    "font-awesome": {
      "main": [
        "scss/**/*.scss",
        "css/font-awesome.css",
        "fonts/**/*"
      ]
    },
    
    
    
    
    "jquery": {
      "main": [
        "dist/jquery.js",
        "dist/jquery.min.js"
      ]
    }
  }
}
```

**Comment by mohamdio** [comment]
Great this should working fine after insert the command, so what you get exact in terminal after insert
` bower install `
also i tested everything from beginning and all working fine, can you try ` slush kickstart ` in the new project folder and let me what will happened ?

**Comment by violacase** [comment]
That's odd. It works on Window 10 but fails on Centos 7. Perhaps it's Slush? Perhaps dependencies? 

I've decided to go for Yeoman gulp-angular. Thanks for your attention.
